# Generated by Django 3.2.9 on 2021-12-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predictor', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('bat_team', models.CharField(max_length=30)),
                ('ball_team', models.CharField(max_length=30)),
                ('overs', models.FloatField()),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('runs_in_prev_5', models.IntegerField()),
                ('wickets_in_prev_5', models.IntegerField()),
                ('logistic_result', models.IntegerField()),
                ('random_forest_result', models.IntegerField()),
                ('knn_result', models.IntegerField()),
            ],
        ),
    ]
