# Generated by Django 3.2.9 on 2021-12-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='ball_team',
            new_name='bowl_team',
        ),
    ]
